# Generated by Django 5.1.2 on 2024-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_father_name_father_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
