# Generated by Django 5.1.2 on 2024-11-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default='nE0QvNpDwD3VGDQ1nZTULCww4SSaDgFDRg8ivkOSzILqSyCNgZxl1nBHjIkQ50YcuMv6uO9H1vuEN6abm8fBkDT3eIqW0NCQnwIz5BdtQ3eTqSAotyNLXYTm2ZhllhA60pxcpCROq0QZP3ZwMmZHxaENSOEo3PSruEm85SX2ZgM1lfSGUgWB93ugOwhekLuRGVj2UCoQ', max_length=300),
        ),
    ]
