# Generated by Django 5.1.2 on 2024-11-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_exceptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
