# Generated by Django 5.1.2 on 2024-11-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_filtering', '0002_category_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=22.99, max_digits=10),
        ),
    ]
