# Generated by Django 5.1.2 on 2024-11-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_filtering', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=2),
        ),
    ]
