# Generated by Django 5.1.2 on 2024-11-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_website',
            field=models.URLField(null=True),
        ),
    ]
