# Generated by Django 5.1.2 on 2024-11-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_external_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='external_website',
            field=models.URLField(error_messages={'invalid': 'The URL provided is not valid. Please provide a valid URL.', 'required': 'The external URL is required.'}, null=True),
        ),
    ]
