# Generated by Django 5.1.2 on 2024-11-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_external_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('admin', 'Administrator'), ('viewer', 'Viewer'), ('editor', 'Editor')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='external_website',
            field=models.URLField(null=True),
        ),
    ]
