# Generated by Django 5.1.2 on 2024-11-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_monitor_alter_post_external_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('published', models.DateField(auto_created=True)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
